// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID          int64
	Title       string
	Description string
	Director    string
	CreatedAt   pgtype.Timestamptz
}

type Rating struct {
	ID        int64
	MovieID   int64
	Rating    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
